set -g default-terminal "screen-256color"
# also enable full RBG colors
#set -ag terminal-overrides ",xterm-256color:RGB"

# preserve CWD
bind '"' split-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# custom color for easier id pink, magenta, grey, gold, green
set -g status-bg magenta

set -sg escape-time 20
#set-option -g allow-rename off

set -g history-limit 10000

# Create and switch to a new session
bind-key S command-prompt -p "New Session Name:" "new-session -s '%%'"

